-- INFO - 15:42:36--03-15-2025:
-- -- 03/14/2025

-- DEBUG - 15:42:36--03-15-2025:
-- -- Starting new HTTPS connection (1): stats.nba.com:443

-- DEBUG - 15:42:37--03-15-2025:
-- -- https://stats.nba.com:443 "GET /stats/leaguegamefinder?Conference=&DateFrom=03%2F14%2F2025&DateTo=03%2F14%2F2025&Division=&DraftNumber=&DraftRound=&DraftTeamID=&DraftYear=&EqAST=&EqBLK=&EqDD=&EqDREB=&EqFG3A=&EqFG3M=&EqFG3_PCT=&EqFGA=&EqFGM=&EqFG_PCT=&EqFTA=&EqFTM=&EqFT_PCT=&EqMINUTES=&EqOREB=&EqPF=&EqPTS=&EqREB=&EqSTL=&EqTD=&EqTOV=&GameID=&GtAST=&GtBLK=&GtDD=&GtDREB=&GtFG3A=&GtFG3M=&GtFG3_PCT=&GtFGA=&GtFGM=&GtFG_PCT=&GtFTA=&GtFTM=&GtFT_PCT=&GtMINUTES=&GtOREB=&GtPF=&GtPTS=&GtREB=&GtSTL=&GtTD=&GtTOV=&LeagueID=00&Location=&LtAST=&LtBLK=&LtDD=&LtDREB=&LtFG3A=&LtFG3M=&LtFG3_PCT=&LtFGA=&LtFGM=&LtFG_PCT=&LtFTA=&LtFTM=&LtFT_PCT=&LtMINUTES=&LtOREB=&LtPF=&LtPTS=&LtREB=&LtSTL=&LtTD=&LtTOV=&Outcome=&PORound=&PlayerID=&PlayerOrTeam=P&RookieYear=&Season=&SeasonSegment=&SeasonType=&StarterBench=&TeamID=&VsConference=&VsDivision=&VsTeamID=&YearsExperience= HTTP/1.1" 200 9096

-- INFO - 15:42:37--03-15-2025:
-- -- Fetched 216 game logs from 03/14/2025

-- INFO - 15:42:37--03-15-2025:
-- -- Cleaning and transforming 216 game logs for insert

-- DEBUG - 15:42:37--03-15-2025:
-- -- Insert statement generated: insert ignore into active_players (player_id, player_name, team_id) values (%s, %s, %s);

-- DEBUG - 15:42:37--03-15-2025:
-- -- Database connection successful: <mariadb.connection connected to 'pi-jdeto' at 000002AD38D55BD0>

-- DEBUG - 15:42:37--03-15-2025:
-- -- Records in active_players before insert: 597

-- DEBUG - 15:42:37--03-15-2025:
-- -- Inserts executed successfully!

-- INFO - 15:42:37--03-15-2025:
-- -- Committed insert of 4 new records into active_players -- 601 records now exist in table

-- DEBUG - 15:42:37--03-15-2025:
-- -- Database connection closed

-- DEBUG - 15:42:37--03-15-2025:
-- -- Insert statement generated: insert ignore into active_teams (team_id, team, team_name) values (%s, %s, %s);

-- DEBUG - 15:42:37--03-15-2025:
-- -- Database connection successful: <mariadb.connection connected to 'pi-jdeto' at 000002AD38D57750>

-- DEBUG - 15:42:37--03-15-2025:
-- -- Records in active_teams before insert: 30

-- DEBUG - 15:42:38--03-15-2025:
-- -- Inserts executed successfully!

-- INFO - 15:42:38--03-15-2025:
-- -- Insert function executed successfully, but no new records were inserted into active_teams

-- DEBUG - 15:42:38--03-15-2025:
-- -- Database connection closed

-- DEBUG - 15:42:38--03-15-2025:
-- -- Insert statement generated: insert ignore into game (game_id, season_id, game_date, matchup, game_type, ot_int, final_score) values (%s, %s, %s, %s, %s, %s, %s);

-- DEBUG - 15:42:38--03-15-2025:
-- -- Database connection successful: <mariadb.connection connected to 'pi-jdeto' at 000002AD38D55BD0>

-- DEBUG - 15:42:38--03-15-2025:
-- -- Records in game before insert: 55

-- ERROR - 15:42:38--03-15-2025:
-- -- Could not insert records:
Traceback (most recent call last):
  File "D:\programming_projects\nba_etl\src\database\dml.py", line 21, in insert_into
    cur.execute(insert_query, value)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "d:\programming_projects\nba_etl\.venv\Lib\site-packages\mariadb\cursors.py", line 313, in execute
    self._execute_binary()
    ~~~~~~~~~~~~~~~~~~~~^^
mariadb.ProgrammingError: Unknown column 'ot_int' in 'INSERT INTO'
-- INFO - 15:42:38--03-15-2025:
-- -- Insert function executed successfully, but no new records were inserted into game

-- DEBUG - 15:42:38--03-15-2025:
-- -- Database connection closed

-- DEBUG - 15:42:38--03-15-2025:
-- -- Insert statement generated: insert ignore into player_box (game_id, player_id, team_id, mins, pts, ast, reb, stl, blk, oreb, dreb, tov, pf) values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);

-- DEBUG - 15:42:38--03-15-2025:
-- -- Database connection successful: <mariadb.connection connected to 'pi-jdeto' at 000002AD38D56E90>

-- DEBUG - 15:42:38--03-15-2025:
-- -- Records in player_box before insert: 1140

-- DEBUG - 15:42:38--03-15-2025:
-- -- Inserts executed successfully!

-- INFO - 15:42:38--03-15-2025:
-- -- Insert function executed successfully, but no new records were inserted into player_box

-- DEBUG - 15:42:38--03-15-2025:
-- -- Database connection closed

-- DEBUG - 15:42:38--03-15-2025:
-- -- Insert statement generated: insert ignore into player_shooting (game_id, player_id, team_id, fgm, fga, fg3m, fg3a, ftm, fta, fg_pct, fg3_pct, ft_pct) values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);

-- DEBUG - 15:42:38--03-15-2025:
-- -- Database connection successful: <mariadb.connection connected to 'pi-jdeto' at 000002AD38D56350>

-- DEBUG - 15:42:38--03-15-2025:
-- -- Records in player_shooting before insert: 0

-- ERROR - 15:42:38--03-15-2025:
-- -- Could not insert records:
Traceback (most recent call last):
  File "D:\programming_projects\nba_etl\src\database\dml.py", line 21, in insert_into
    cur.execute(insert_query, value)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "d:\programming_projects\nba_etl\.venv\Lib\site-packages\mariadb\cursors.py", line 313, in execute
    self._execute_binary()
    ~~~~~~~~~~~~~~~~~~~~^^
mariadb.ProgrammingError: Unknown column 'fg_pct' in 'INSERT INTO'
-- INFO - 15:42:38--03-15-2025:
-- -- Insert function executed successfully, but no new records were inserted into player_shooting

-- DEBUG - 15:42:38--03-15-2025:
-- -- Database connection closed

-- DEBUG - 15:42:38--03-15-2025:
-- -- Insert statement generated: insert ignore into team_box (game_id, team_id, mins, pts, ast, reb, stl, blk, oreb, dreb, tov, pf) values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);

-- DEBUG - 15:42:38--03-15-2025:
-- -- Database connection successful: <mariadb.connection connected to 'pi-jdeto' at 000002AD38D57110>

-- DEBUG - 15:42:38--03-15-2025:
-- -- Records in team_box before insert: 0

-- DEBUG - 15:42:38--03-15-2025:
-- -- Inserts executed successfully!

-- INFO - 15:42:38--03-15-2025:
-- -- Insert function executed successfully, but no new records were inserted into team_box

-- DEBUG - 15:42:38--03-15-2025:
-- -- Database connection closed

-- DEBUG - 15:42:38--03-15-2025:
-- -- Insert statement generated: insert ignore into team_shooting (game_id, team_id, fgm, fga, fg3m, fg3a, ftm, fta, fg_pct, fg3_pct, ft_pct) values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);

-- DEBUG - 15:42:38--03-15-2025:
-- -- Database connection successful: <mariadb.connection connected to 'pi-jdeto' at 000002AD38D57250>

-- DEBUG - 15:42:38--03-15-2025:
-- -- Records in team_shooting before insert: 0

-- ERROR - 15:42:38--03-15-2025:
-- -- Could not insert records:
Traceback (most recent call last):
  File "D:\programming_projects\nba_etl\src\database\dml.py", line 21, in insert_into
    cur.execute(insert_query, value)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "d:\programming_projects\nba_etl\.venv\Lib\site-packages\mariadb\cursors.py", line 313, in execute
    self._execute_binary()
    ~~~~~~~~~~~~~~~~~~~~^^
mariadb.ProgrammingError: Unknown column 'fg_pct' in 'INSERT INTO'
-- INFO - 15:42:38--03-15-2025:
-- -- Insert function executed successfully, but no new records were inserted into team_shooting

-- DEBUG - 15:42:38--03-15-2025:
-- -- Database connection closed

-- DEBUG - 15:42:38--03-15-2025:
-- -- Insert statement generated: insert ignore into team_gamelog (game_id, team_id, win_ind, home_ind) values (%s, %s, %s, %s);

-- DEBUG - 15:42:38--03-15-2025:
-- -- Database connection successful: <mariadb.connection connected to 'pi-jdeto' at 000002AD38D56D50>

-- DEBUG - 15:42:38--03-15-2025:
-- -- Records in team_gamelog before insert: 0

-- DEBUG - 15:42:38--03-15-2025:
-- -- Inserts executed successfully!

-- INFO - 15:42:38--03-15-2025:
-- -- Insert function executed successfully, but no new records were inserted into team_gamelog

-- DEBUG - 15:42:38--03-15-2025:
-- -- Database connection closed

